In [95]:
import pandas as pd
from pathlib import Path
import numpy as np

In [96]:
path_root = Path(r'\\rad-maid-004\D\PENN-MRI\label_added_dummy_ehr_new.csv')
df = pd.read_csv(path_root)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6175 entries, 0 to 6174
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dummy_acc                       6175 non-null   int64
 1   studyleveloutcome               4431 non-null   object
 2   componentleveloutcome           4431 non-null   object
 3   studylevelassessment            6015 non-null   object
 4   componentlevelassessment        6015 non-null   object
 5   recommendation                  6072 non-null   object
 6   BreastMriIndicationText         5730 non-null   object
 7   Narrative                       6172 non-null   object
 8   ageAtDiagnosis                  859 non-null    float64
 9   primarysite                     859 non-null    object
 10  primarySiteDescription          859 non-null    object
 11  laterality                      859 non-null    float64
 12  lateralityDescription           859 non-null    object
 13  histologicTypeIcdO3             859 non-null    float64
 14  histologicTypeIcdO3Description  844 non-null    object
 15  behaviorCodeIcdO3               859 non-null    float64
 16  behaviorCodeIcdO3Description    859 non-null    object
 17  grade                           347 non-null    float64
 18  gradeDescription                347 non-null    object
 19  bc_prior                        6175 non-null   int64
 20  label                           6015 non-null   object
dtypes: float64(5), int64(2), object(14)
memory usage: 1013.2+ KB

In [97]:
df.head()

,dummy_acc,studyleveloutcome,componentleveloutcome,studylevelassessment,componentlevelassessment,recommendation,BreastMriIndicationText,Narrative,ageAtDiagnosis,primarysite,...,laterality,lateralityDescription,histologicTypeIcdO3,histologicTypeIcdO3Description,behaviorCodeIcdO3,behaviorCodeIcdO3Description,grade,gradeDescription,bc_prior,label
0,83073156,NaN,NaN,6: Known Biopsy-Proven Malignancy,Known Biopsy-Proven Malignancy [6],"MR Normal, _x000D__x000D__x000D__x000D__x000D_...",Staging evaluation of new breast cancer.,BREAST MRI INDICATION: Staging evaluation of n...,62.0,C509,...,1.0,Right: origin of primary,8500.0,"Intraductal adenocarcinoma, noninfiltrating, NOS",2.0,Carcinoma in situ; intraepithelial; noninfiltr...,1.0,Grade I,1,Known Biopsy-Proven Malignancy
1,21737705,NaN,NaN,6: Known Biopsy-Proven Malignancy,Known Biopsy-Proven Malignancy [6],"Appropriate action should be taken, _x000D__x0...",Staging evaluation of new breast cancer.,BREAST MRI INDICATION: Staging evaluation of n...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Known Biopsy-Proven Malignancy
2,77713151,TN,TN,2: Benign,Benign [2],MR Normal,High risk screening.,BREAST MRI INDICATION: High risk screening. H...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Benign
3,71362839,TN,TN,1: Negative,Negative [1],MR Normal,High risk screening.,BREAST MRI INDICATION: High risk screening. H...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Negative
4,44839460,TN,TN,2: Benign,Benign [2],MR Normal,High risk screening.,BREAST MRI INDICATION: High risk screening. H...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,Benign

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6175 entries, 0 to 6174
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dummy_acc                       6175 non-null   int64
 1   studyleveloutcome               4431 non-null   object
 2   componentleveloutcome           4431 non-null   object
 3   studylevelassessment            6015 non-null   object
 4   componentlevelassessment        6015 non-null   object
 5   recommendation                  6072 non-null   object
 6   BreastMriIndicationText         5730 non-null   object
 7   Narrative                       6172 non-null   object
 8   ageAtDiagnosis                  859 non-null    float64
 9   primarysite                     859 non-null    object
 10  primarySiteDescription          859 non-null    object
 11  laterality                      859 non-null    float64
 12  lateralityDescription           859 non-null    object
 13  histologicTypeIcdO3             859 non-null    float64
 14  histologicTypeIcdO3Description  844 non-null    object
 15  behaviorCodeIcdO3               859 non-null    float64
 16  behaviorCodeIcdO3Description    859 non-null    object
 17  grade                           347 non-null    float64
 18  gradeDescription                347 non-null    object
 19  bc_prior                        6175 non-null   int64
 20  label                           6015 non-null   object
dtypes: float64(5), int64(2), object(14)
memory usage: 1013.2+ KB

In [99]:
df['label'].value_counts()

Benign                                2418
Negative                              2313
Suspicious                             566
Known Biopsy-Proven Malignancy         323
Probably Benign                        321
Need Additional Imaging Evaluation      47
Highly Suggestive of Malignancy         27
Name: label, dtype: int64

In [100]:
df = df[~((df['label'] == 'Highly Suggestive of Malignancy') & (df['laterality'].isna()))]
df = df[~((df['label'] == 'Suspicious') & (df['laterality'].isna()))]

In [101]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5817 entries, 0 to 6174
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dummy_acc                       5817 non-null   int64
 1   studyleveloutcome               4137 non-null   object
 2   componentleveloutcome           4137 non-null   object
 3   studylevelassessment            5657 non-null   object
 4   componentlevelassessment        5657 non-null   object
 5   recommendation                  5714 non-null   object
 6   BreastMriIndicationText         5393 non-null   object
 7   Narrative                       5814 non-null   object
 8   ageAtDiagnosis                  859 non-null    float64
 9   primarysite                     859 non-null    object
 10  primarySiteDescription          859 non-null    object
 11  laterality                      859 non-null    float64
 12  lateralityDescription           859 non-null    object
 13  histologicTypeIcdO3             859 non-null    float64
 14  histologicTypeIcdO3Description  844 non-null    object
 15  behaviorCodeIcdO3               859 non-null    float64
 16  behaviorCodeIcdO3Description    859 non-null    object
 17  grade                           347 non-null    float64
 18  gradeDescription                347 non-null    object
 19  bc_prior                        5817 non-null   int64
 20  label                           5657 non-null   object
dtypes: float64(5), int64(2), object(14)
memory usage: 999.8+ KB

In [102]:
df['label'].value_counts()

Benign                                2418
Negative                              2313
Known Biopsy-Proven Malignancy         323
Probably Benign                        321
Suspicious                             214
Need Additional Imaging Evaluation      47
Highly Suggestive of Malignancy         21
Name: label, dtype: int64

In [105]:
df = df[df['label'] != 'normal']

In [106]:
df.to_csv("preprocessed_mapped_patient_info_nosurv.csv")

In [107]:
split_data_path = Path(r"\\rad-maid-004\D\PENN-MRI\penn-preprocessed_cropped2\penn-preprocessed_datasplit.csv")
split_data = pd.read_csv(split_data_path)
split_data

,dummy_acc,UID,side,laterality,label,Malignant,Fold,Split
0,10103721,10103721_left,left,1.0,benign,0,0,test
1,10103721,10103721_right,right,1.0,benign,0,0,test
2,11154092,11154092_left,left,2.0,benign,0,0,test
3,11154092,11154092_right,right,1.0,benign,0,0,test
4,11374654,11374654_left,left,2.0,birads_4_benign,0,0,test
...,...,...,...,...,...,...,...,...
385,88240033,88240033_left,left,2.0,benign,0,0,test
386,88993783,88993783_left,left,1.0,birads_4_benign,0,0,test
387,88993783,88993783_right,right,1.0,birads_4_benign,0,0,test
388,89111504,89111504_left,left,2.0,benign,0,0,test
389,89111504,89111504_right,right,2.0,benign,0,0,test

In [108]:
split_data = split_data[split_data['label'].isin(['birads_4_benign', 'benign', 'birads_4_malignant', 'malignant'])]
split_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dummy_acc   390 non-null    int64
 1   UID         390 non-null    object
 2   side        390 non-null    object
 3   laterality  390 non-null    float64
 4   label       390 non-null    object
 5   Malignant   390 non-null    int64
 6   Fold        390 non-null    int64
 7   Split       390 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 27.4+ KB

In [109]:
split_data = split_data.drop_duplicates('UID')

split_data.sort_values(by='dummy_acc', inplace=True)
split_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dummy_acc   390 non-null    int64
 1   UID         390 non-null    object
 2   side        390 non-null    object
 3   laterality  390 non-null    float64
 4   label       390 non-null    object
 5   Malignant   390 non-null    int64
 6   Fold        390 non-null    int64
 7   Split       390 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 27.4+ KB

In [110]:
excl_path = Path(r"D:\Users\UFPB\gabriel ayres\MST\scripts\preprocessing\penn-preprocessed\to_exclude.txt")
csv_path = Path(r'D:\Users\UFPB\gabriel ayres\MST\notebooks\penn-preprocessed_datasplit.csv') # Make sure this path is correct

split_data = pd.read_csv(csv_path)
print(f"--- Before filtering, DataFrame has {len(split_data)} rows. ---")

with open(excl_path, 'r') as f:
    exclude_uids = [line.split(' - ')[0].strip() for line in f if line.strip()]

split_data = split_data[~split_data['UID'].astype(str).isin(exclude_uids)]

# Verify the result
print(f"--- After filtering, DataFrame has {len(split_data)} rows. ---")
split_data.info()

--- Before filtering, DataFrame has 390 rows. ---
--- After filtering, DataFrame has 390 rows. ---
<class 'pandas.core.frame.DataFrame'>
Int64Index: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dummy_acc   390 non-null    int64
 1   UID         390 non-null    object
 2   side        390 non-null    object
 3   laterality  390 non-null    float64
 4   label       390 non-null    object
 5   Malignant   390 non-null    int64
 6   Fold        390 non-null    int64
 7   Split       390 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 27.4+ KB

In [111]:
split_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 390 entries, 0 to 389
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   dummy_acc   390 non-null    int64
 1   UID         390 non-null    object
 2   side        390 non-null    object
 3   laterality  390 non-null    float64
 4   label       390 non-null    object
 5   Malignant   390 non-null    int64
 6   Fold        390 non-null    int64
 7   Split       390 non-null    object
dtypes: float64(1), int64(3), object(4)
memory usage: 27.4+ KB

In [112]:
#split_data.to_csv('penn-preprocessed_datasplit.csv', index=False)

In [113]:
print((exclude))

['1', '1', '8', '2', '6', '9', '9', '5', '_', 'l', 'e', 'f', 't']